### ISSUE TITLE
Automate python env installation

### ISSUE THREAD

**Issue by tomijaroli** [tomijaroli/dotfiles#5]
## Description
Automate installing python environment by migrating the existing [installation gist](https://gist.github.com/tomijaroli/fa4938219ecac6951da3ae84ed9e5877) to the install script.

ZSH configuration part is already migrated to the dotfiles.

## Tasks
- [ ] Add `python-virtualenv` installation to the install script
- [ ] Reinstall `bzip2` and `zlib` if necessary
- [ ] Install [xxenv-latest](https://github.com/momo-lab/xxenv-latest) tool
- [ ] Install latest python version 

## Component or tool
- installation
- pyenv
