### ISSUE TITLE
Automate ruby env installation

### ISSUE THREAD

**Issue by tomijaroli** [tomijaroli/dotfiles#6]
## Description
Automate installing ruby environment by migrating the existing [installation gist](https://gist.github.com/tomijaroli/1b61362423906bacd57f0041b7e88708) to the install script.

ZSH configuration part is already migrated to the dotfiles.

## Tasks
- [ ] Install [xxenv-latest](https://github.com/momo-lab/xxenv-latest) tool
- [ ] Install the latest ruby version
- [ ] Install and setup gems
- [ ] Install bundler
- [ ] Bundler optimization

## Component or tool
- installation
- rbenv
